--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimplePets
build-by-default: true
branches:
- master

projects:
  SimplePets:
    icon: "/assets/logo-min.png"
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.4.0
        branch: "4.0"
      - src: muqsit/InvMenu/InvMenu
        version: ^4.3.2
        branch: "4.0"
    lint:
      phpstan: false
...
