name: SimplePets
main: brokiem\simplepets\SimplePets
version: 1.0.4-beta
api: 3.20.0
mcpe-protocol: [ 440, 448, 465, 471 ]
authors: [ "broki", "brokiem", "broski" ]

website: https://github.com/brokiem/SimplePets

extensions:
  Core: '>=7.4'

permissions:
  simplepets.spawn:
    default: op
  simplepets.remove:
    default: op
  simplepets.inv:
    default: true
  simplepets.inv.other:
    default: op
  simplepets.ride:
    default: true
  simplepets.petlist:
    default: op
  simplepets.notify:
    default: op