name: SimplePets
main: brokiem\simplepets\SimplePets
version: 1.0.0-beta
api: 3.22.0
mcpe-protocols: [ 448 ]
authors: [ "broki", "brokiem", "broski" ]

website: https://github.com/brokiem/SimplePets

extensions:
  Core: '>=8.0'

permissions:
  simplepets.spawn:
    default: op
  simplepets.remove:
    default: op
  simplepets.inv:
    default: true
  simplepets.ride:
    default: true